---
# defaults file for ./docker-setup
deb_architecture: {
  "aarch64": "arm64",
  "x86_64": "amd64"
}

# docker image mirror
registr_mirrors: https://docker.arvancloud.ir

# docker required packages
docker_required_packages_list:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools
  - pip