- name: Create a directory /opt/services if it does not exist
  ansible.builtin.file:
    path: /opt/services
    state: directory
    mode: '0755'

- name: Move script file
  copy:
    src: log_sender.sh
    dest: /usr/local/bin/log_sender.sh
    mode: '0755'

- name: Move systemd service file
  copy:
    src: log_sender.service
    dest: /etc/systemd/system/log_sender.service
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Start and enable the log_sender service
  systemd:
    name: log_sender
    state: started
    enabled: yes

- name: Move rsyslog configuration files
  copy:
    src: log/
    dest: /opt/services
    mode: '0755'

- name: Start services
  community.docker.docker_compose_v2:
    project_src: "/opt/services/"
    build: always
  tags: docker

- name: Execute elastic policy from bash script
  ansible.builtin.shell: /opt/services/life-cycle.sh
